### ISSUE TITLE
Change Page Help

### ISSUE THREAD

**Issue by mkeigwin** [mkeigwin/meme-generator#1]
@rapala61
I've been working on making a button to change the page number in the api query strings. The trouble I'm running into is that I am searching 2 API's at the same time so the names the API's gave to changing the page are different here is what I've tried in the html so far to create button that changes page
<img width="358" alt="screen shot 2016-10-27 at 10 48 01 am" src="https://cloud.githubusercontent.com/assets/22108001/19773012/ff4bd00c-9c35-11e6-87c5-df7ee2d663f9.png">

and this is what my 2 api look like

function searchGif (req, res, next) { const qs = req.body.search; let page = 0; // let page = req.query.page = 0; let number = req.query.number = 12; fetch(${API_URL}q=${qs}&api_key=dc6zaTOxFJmzC&limit=${number}&offset=${page}`)

function searchMeme (req, res, next) {
const qs = req.body.search;
let page = 0;
// let page = req.query.page = 0;
let number = req.query.number = 12;
fetch(${API_URL}q=${qs}&pageIndex=${page}&pageSize=${number})`

Thanks for any and all help

**Comment by rapala61** [comment]
Lets meet after lunch for a few minutes.
